### ISSUE TITLE
Should the img tag be included?

### ISSUE THREAD

**Issue by ADTTheodore** [Gillespie59/10K-Project#4]
Firstly, I like your idea!

While I was looking at it, I tried the `<img />` tag and noticed it didn't return any attributes. In fact it tells me the tag doesn't exist.

Should it be added?

**Comment by gericci** [comment]
Hi, Theodore
Thanks for pointing it out! Indeed the IMG tag is not in our list (don't know why..) I'll check it asap and check if other elements are missing. cheers!

**Comment by jpdevries** [comment]
I noticed this as well, but haven't noticed any other missing tags. If I do I'll point them out.

I hope you don't mind I borrowed your `.json` files to easily generate a collection of Twig includes for each HTML tag https://github.com/jpdevries/Twag

**Comment by gericci** [comment]
Hi, thanks for that, JP
Yes, of course, you can use the json files. I've just addded the json for the missing IMG element also.
