### ISSUE TITLE
Missing Tags?

### ISSUE THREAD

**Issue by jpdevries** [Gillespie59/10K-Project#5]
- `<svg>`
- `<use>`

**Comment by gericci** [comment]
Thanks @jpdevries. I'll add them too and check why those elements didn't get in the list

**Comment by EmmanuelDemey** [comment]
I use the element list from MDN : https://developer.mozilla.org/fr/docs/Web/HTML/Element

SVG and Use elements are not listed . 

I will add these two manually

**Comment by gericci** [comment]
You're right, @Gillespie59. The svg element is part of the SVG specs, so, technically, it is not a HTML element (as it has a spec of its own). I could not find any reference for element <use> -- and I didn't know it existed. Do you have any reference for it, @jpdevries ?

**Comment by jpdevries** [comment]
@gericci I think the tricky thing about SVG is as you point out it has its own spec, and a bunch of unique tags. So you kind of open up a can of worms if you were to start adding all the SVG elements.

**Comment by gericci** [comment]
@jpdevries exactly. So we'd better not include it on the list. @Gillespie59
